spring:
    profiles: dev
    message: Post Service - dev - Spring Cloud Bus, RabbitMQ 연동 Test!
    sleuth:
        sampler:
            probability: 1.0
    zipkin:
        base-url: http://localhost:9411
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka