spring:
  application:
    name: post-service
  sleuth:
    sampler:
      probability: 1.0 #어플리케이션으로 오늘 요청 중 초당 몇 퍼센트나 트렌잭션 정보를 외부로 전달할지 설정한다. 0.0 ~ 1.0 값을 사용할 수 있으며 디폴트는 0.1 (10%)이다.
  zipkin:
    base-url: http://localhost:9411
server:
  port: 9001
logging:
  level:
    ROOT: info
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka